module Spree::CurrencyToCountry
  extend ActiveSupport::Concern

  CURRENCY_TO_COUNTRY_ISO_MAP = {
      AED: %w(AE),
      AFN: %w(AF),
      ALL: %w(AL),
      AMD: %w(AM),
      ANG: %w(CW SX),
      AOA: %w(AO),
      ARS: %w(AR),
      AUD: %w(AU CX CC HM KI NR NF TV),
      AWG: %w(AW),
      AZN: %w(AZ),
      BAM: %w(BA),
      BBD: %w(BB),
      BDT: %w(BD),
      BGN: %w(BG),
      BHD: %w(BH),
      BIF: %w(BI),
      BMD: %w(BM),
      BND: %w(BN),
      BOB: %w(BO),
      BRL: %w(BR),
      BSD: %w(BS),
      BTN: %w(BT),
      BWP: %w(BW),
      BYN: %w(BY),
      BZD: %w(BZ),
      CAD: %w(CA),
      CDF: %w(CD),
      CHF: %w(LI CH),
      CLP: %w(CL),
      CNY: %w(CN),
      COP: %w(CO),
      CRC: %w(CR),
      CUC: %w(CU),
      CUP: %w(CU),
      CVE: %w(CV),
      CZK: %w(CZ),
      DJF: %w(DJ),
      DKK: %w(DK FO GL),
      DOP: %w(DO),
      DZD: %w(DZ),
      EGP: %w(EG),
      ERN: %w(ER),
      ETB: %w(ET),
      EUR: %w(FR AD AT BE CY EE FI GF TF DE GR GP VA IE IT LV LT LU MT MQ YT MC ME NL PT RE BL MF PM SM SK SI ES AX PS),
      FJD: %w(FJ),
      FKP: %w(FK),
      GBP: %w(GG IM JE GB GS),
      GEL: %w(GE),
      GHS: %w(GH),
      GIP: %w(GI),
      GMD: %w(GM),
      GNF: %w(GN),
      GTQ: %w(GT),
      GYD: %w(GY),
      HKD: %w(HK),
      HNL: %w(HN),
      HRK: %w(HR),
      HTG: %w(HT),
      HUF: %w(HU),
      IDR: %w(ID),
      ILS: %w(IL),
      INR: %w(IN BT),
      IQD: %w(IQ),
      IRR: %w(IR),
      ISK: %w(IS),
      JMD: %w(JM),
      JOD: %w(JO),
      JPY: %w(JP),
      KES: %w(KE),
      KGS: %w(KG),
      KHR: %w(KH),
      KMF: %w(KM),
      KPW: %w(KP),
      KRW: %w(KR),
      KWD: %w(KW),
      KYD: %w(KY),
      KZT: %w(KZ),
      LAK: %w(LA),
      LBP: %w(LB),
      LKR: %w(LK),
      LRD: %w(LR),
      LSL: %w(LS),
      LYD: %w(LY),
      MAD: %w(MA EH),
      MDL: %w(MD),
      MGA: %w(MG),
      MKD: %w(MK),
      MMK: %w(MM),
      MNT: %w(MN),
      MOP: %w(MO),
      MRO: %w(MR),
      MUR: %w(MU),
      MVR: %w(MV),
      MWK: %w(MW),
      MXN: %w(MX),
      MYR: %w(MY),
      MZN: %w(MZ),
      NAD: %w(NA),
      NGN: %w(NG),
      NIO: %w(NI),
      NOK: %w(BV NO SJ),
      NPR: %w(NP),
      NZD: %w(CK NZ NU PN TK),
      OMR: %w(OM),
      PAB: %w(PA),
      PEN: %w(PE),
      PGK: %w(PG),
      PHP: %w(PH),
      PKR: %w(PK),
      PLN: %w(PL),
      PYG: %w(PY),
      QAR: %w(QA),
      RON: %w(RO),
      RSD: %w(RS),
      RUB: %w(RU),
      RWF: %w(RW),
      SAR: %w(SA),
      SBD: %w(SB),
      SCR: %w(SC),
      SDG: %w(SD),
      SEK: %w(SE),
      SGD: %w(SG),
      SHP: %w(SH),
      SLL: %w(SL),
      SOS: %w(SO),
      SRD: %w(SR),
      SSP: %w(SS),
      STD: %w(ST),
      SVC: %w(SV),
      SYP: %w(SY),
      SZL: %w(SZ),
      THB: %w(TH),
      TJS: %w(TJ),
      TMT: %w(TM),
      TND: %w(TN),
      TOP: %w(TO),
      TRY: %w(TR),
      TTD: %w(TT),
      TWD: %w(TW),
      TZS: %w(TZ),
      UAH: %w(UA),
      UGX: %w(UG),
      USD: %w(US HT PA SV AS BQ IO VG EC GU MH FM MP PW PR TL TC UM VI AQ PS),
      UYU: %w(UY),
      UZS: %w(UZ),
      VEF: %w(VE),
      VND: %w(VN),
      VUV: %w(VU),
      WST: %w(WS),
      XAF: %w(CM CF TD CG GQ GA),
      XCD: %w(AI AG DM GD MS KN LC VC),
      XOF: %w(BJ BF CI GW ML NE SN TG),
      XPF: %w(PF NC WF),
      YER: %w(YE),
      ZAR: %w(LS NA ZA),
      ZMW: %w(ZM),
      ZWL: %w(ZW),
  }
end